#!/bin/bash

APP_NAME="JankTerm"
SCRIPT_DIR="$(dirname "$(realpath "$0")")"
BASE_PATH="$SCRIPT_DIR/.."
OLD_EXEC_PATH="$BASE_PATH/build/term"
EXEC_PATH="/usr/bin/jankterm"
ICON_PATH="$BASE_PATH/assets/jank_term.png"
DESKTOP_FILE="/usr/share/applications/term.desktop"
VERSION=1.0

cp $OLD_EXEC_PATH $EXEC_PATH

echo "[Desktop Entry]" > $DESKTOP_FILE
echo "Version=$VERSION" >> $DESKTOP_FILE
echo "Name=$APP_NAME" >> $DESKTOP_FILE
echo "Comment=JankTerminal" >> $DESKTOP_FILE
echo "Exec=$EXEC_PATH" >> $DESKTOP_FILE
echo "Icon=$ICON_PATH" >> $DESKTOP_FILE
echo "Terminal=false" >> $DESKTOP_FILE
echo "Type=Application" >> $DESKTOP_FILE
echo "Categories=Utility;Application;" >> $DESKTOP_FILE

chmod +x $DESKTOP_FILE

echo "Application created successfully!"
